# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 12:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='domain',
        ),
        migrations.AddField(
            model_name='post',
            name='content_type',
            field=models.TextField(default=datetime.datetime(2016, 7, 23, 12, 57, 8, 686957, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='request_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
